"""Collect on-policy rollouts by running the base VLA (pi05) in the VLABench sim, and save the
SUCCESS trajectories as a proprio feature cache for fine-tuning the action predictor.

Motivation: the predictor is trained on demonstrations but, at deployment, conditions on states
the base VLA visits (covariate shift). Behaviour-cloning the predictor on (state, VLA-action)
pairs from the VLA's *own* successful rollouts moves its training distribution toward deployment.

Each episode is generated by seed (``--seed-base + i``), kept disjoint from the eval track. Per
step we record ``state`` (the predictor's 7-D input, identical convention to demos) and the raw
7-D VLA action it executed. After the episode the env reports success; we save one npz per episode
(same schema as ``proprio_features``: states/actions[+is_success]) plus an ``index.json``.

Reuses the VLABench ``Evaluator.evaluate_single_episode`` (env/step/success/seed) and live_eval's
state extraction, so the rollout dynamics match the closed-loop eval exactly.

Usage (needs a running pi05 server):
    python -m r3m_action_predictor.collect_rollouts --task select_fruit \
        --host 127.0.0.1 --port 8011 --replan-steps 10 \
        --n-episodes 100 --seed-base 1000 --out-dir <rollout_features_dir>
"""

from __future__ import annotations

import argparse
import collections
import json
from pathlib import Path

import numpy as np
from openpi_client import websocket_client_policy as _websocket_client_policy
from VLABench.evaluation.evaluator import Evaluator
from VLABench.evaluation.model.policy.base import Policy
from VLABench.robots import *  # noqa: F403,F401 - registers robots for load_env
from VLABench.tasks import *  # noqa: F403,F401 - registers tasks for load_env

from .live_eval import _policy_state_from_obs

# VLABench's intention-score diagnostic indexes ``intention_distance`` by the target entity, which is
# KeyError-absent when that entity falls into the task's randomly-ignored set (observed on seed-
# generated select_poker scenes, e.g. target '3_of_diamonds'). evaluate_single_episode computes it
# AFTER the episode has finished and ``success`` is already decided (env termination), then crashes
# before returning -- which would abort the whole rollout collection. We never use intention_score
# for collection (only success + the executed trajectory), so make the lookup KeyError-safe. This is
# scoped to this process; VLABench itself and examples/vlabench/eval.py are untouched.
from VLABench.tasks.hierarchical_tasks.primitive.base import PrimitiveTask as _PrimitiveTask

_orig_intention_to_entity = _PrimitiveTask.get_intention_score_to_entity


def _safe_intention_score_to_entity(self, physics, entity_name, threshold=0.2, discrete=False):
    try:
        return _orig_intention_to_entity(self, physics, entity_name, threshold, discrete)
    except KeyError:
        return 0


_PrimitiveTask.get_intention_score_to_entity = _safe_intention_score_to_entity


class VLARolloutPolicy(Policy):
    """Pure base-VLA policy that records per-step (state, raw 7-D action) for the current episode.

    Same VLA call / action-group conversion as live_eval's VLA path (so rollouts match eval), but
    no predictor/gate. ``pop_episode`` returns and clears the buffered trajectory."""

    def __init__(self, client, replan_steps: int):
        self.model = client
        self.replan_steps = replan_steps
        self.action_plan: collections.deque = collections.deque()
        self._states: list[np.ndarray] = []
        self._actions: list[np.ndarray] = []

    def reset(self):
        self.action_plan.clear()
        self._states.clear()
        self._actions.clear()

    def predict(self, obs, **kwargs):
        state = _policy_state_from_obs(obs)
        if len(self.action_plan) == 0:
            second_image, _, image, image_wrist = obs["rgb"]
            chunk = np.asarray(
                self.model.infer(
                    {
                        "observation/image": image,
                        "observation/second_image": second_image,
                        "observation/wrist_image": image_wrist,
                        "observation/state": state,
                        "prompt": obs["instruction"],
                    }
                )["actions"],
                dtype=np.float32,
            )
            if len(chunk) < self.replan_steps:
                raise RuntimeError(f"VLA returned {len(chunk)} actions < replan_steps {self.replan_steps}")
            self.action_plan.extend(chunk[: self.replan_steps])
        action = np.asarray(self.action_plan.popleft(), dtype=np.float32)
        self._states.append(state.astype(np.float32))
        self._actions.append(action.copy())
        target_pos, target_euler, gripper = action[:3], action[3:6], float(action[-1])
        gripper_state = np.ones(2) * 0.04 if gripper >= 0.1 else np.zeros(2)
        abs_target_pos = target_pos.copy() + obs["robot_frame"]
        return abs_target_pos, target_euler, gripper_state

    def pop_episode(self) -> tuple[np.ndarray, np.ndarray]:
        states = np.asarray(self._states, dtype=np.float32)
        actions = np.asarray(self._actions, dtype=np.float32)
        self._states.clear()
        self._actions.clear()
        self.action_plan.clear()
        return states, actions

    @property
    def name(self):
        return "pi05_vla_rollout_collector"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--task", required=True)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8011)
    ap.add_argument("--replan-steps", type=int, default=10)
    ap.add_argument("--n-episodes", type=int, default=100)
    ap.add_argument("--seed-base", type=int, default=1000,
                    help="Episode i uses seed = seed_base + i. Keep disjoint from the eval seeds.")
    ap.add_argument("--max-episode-length", type=int, default=200)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--save-video", action="store_true")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    client = _websocket_client_policy.WebsocketClientPolicy(args.host, args.port)
    agent = VLARolloutPolicy(client, replan_steps=args.replan_steps)
    evaluator = Evaluator(
        tasks=[args.task], n_episodes=args.n_episodes, episode_config=None, max_substeps=1,
        save_dir=str(out_dir / "_eval") if args.save_video else None, visulization=args.save_video,
        metrics=["success_rate"],
    )

    # Merge into an existing cache if present: keep prior episodes, skip already-collected seeds
    # (resumable), and append the new batch. This lets "collect more with fresh seeds" accumulate.
    index_path = out_dir / "index.json"
    existing = json.loads(index_path.read_text())["episodes"] if index_path.exists() else []
    existing_seeds = {int(e["episode_index"]) for e in existing}
    if existing:
        print(f"merging into existing cache: {len(existing)} episodes "
              f"({sum(e.get('is_success', False) for e in existing)} success)", flush=True)

    new_eps = []
    n_success = 0
    for i in range(args.n_episodes):
        seed = args.seed_base + i
        if seed in existing_seeds:
            print(f"[{i+1}/{args.n_episodes}] seed={seed} already collected -> skip", flush=True)
            continue
        agent.reset()
        info = evaluator.evaluate_single_episode(
            agent, args.task, episode_id=seed, episode_config=None, seed=seed,
            max_episode_length=args.max_episode_length,
        )
        states, actions = agent.pop_episode()
        is_success = bool(info.get("success", False))
        n_success += int(is_success)
        fname = f"ep_{seed:06d}.npz"
        np.savez(
            out_dir / fname,
            states=states, actions=actions,
            episode_index=np.int64(seed), task=np.asarray(args.task),
            is_success=np.bool_(is_success),
        )
        new_eps.append({"episode_index": seed, "file": fname, "T": int(states.shape[0]),
                        "is_success": is_success, "task": args.task})
        print(f"[{i+1}/{args.n_episodes}] seed={seed} T={states.shape[0]} success={is_success} "
              f"(new-batch success {n_success})", flush=True)

    episodes = existing + new_eps
    total_success = sum(e.get("is_success", False) for e in episodes)
    index = {"task": args.task, "n_episodes": len(episodes), "n_success": int(total_success),
             "replan_steps": args.replan_steps, "episodes": episodes}
    index_path.write_text(json.dumps(index, indent=2) + "\n")
    print(f"DONE: new batch {n_success} success / {len(new_eps)} | "
          f"total {total_success} success / {len(episodes)} -> {out_dir}", flush=True)


if __name__ == "__main__":
    main()
